name: ndt_7_dart
description: NDT-7 implemented in Dart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  http: ^0.13.4
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.2
